<?php

namespace App\Models\HRU;

use App\Models\PPU\PPURespCodes;
use App\Models\Scopes\ProjectScope;
use Illuminate\Database\Eloquent\Model;

class PayrollTree extends Model
{
    protected $table = 'hr_pay_tree';

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ProjectScope());
    }

    public function responsibilityCenter(){
        return $this->hasOne(PPURespCodes::class,'rc_code','resp_center');
    }
}